name: yinzlang-staging
region: nyc
services: []
static_sites:
  - name: web
    source_dir: /
    dockerfile_path: website/Dockerfile
    build_command: ""
    output_dir: ""
    routes:
      - path: /
    environment_slug: html
    github:
      repo: yinzers/yinz-lang
      branch: main
      deploy_on_push: true
