[workspace]
resolver = "2"
members = [
    "crates/ynz-driver",
    "crates/ynz-diagnostics",
    "crates/ynz-ast",
    "crates/ynz-parser",
    "crates/ynz-typeck",
    "crates/ynz-codegen",
    "crates/ynz-numerics",
    "crates/ynz-runtime",
    "crates/ynz-registry",
    "crates/ynz-lsp",
    "crates/ynz-tmgrammar",
    "crates/ynz-fmt",
]

[workspace.package]
version = "0.2.0-m2"
edition = "2021"
rust-version = "1.80"
authors = ["The Yinz Contributors"]
license = "MIT OR Apache-2.0"

[workspace.dependencies]
salsa = "0.26.2"
inkwell = { version = "0.9.0", features = ["llvm18-1-prefer-dynamic"] }
ariadne = "0.6.0"
unicode-segmentation = "1.13.2"
insta = { version = "1.47.2", features = ["redactions"] }
clap = { version = "4.6.1", features = ["derive"] }

proptest = { version = "1.6.0", default-features = false, features = ["std"] }
tempfile = "3.14.0"
assert_cmd = "2"

# Cross-crate workspace deps
ynz-registry    = { path = "crates/ynz-registry" }
ynz-diagnostics = { path = "crates/ynz-diagnostics" }
ynz-ast          = { path = "crates/ynz-ast" }
ynz-parser       = { path = "crates/ynz-parser" }
ynz-typeck       = { path = "crates/ynz-typeck" }
ynz-codegen      = { path = "crates/ynz-codegen" }
ynz-numerics     = { path = "crates/ynz-numerics" }
ynz-fmt          = { path = "crates/ynz-fmt" }
