use std::collections::HashSet;
use std::fmt::Write as FmtWrite;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let toml_path = manifest_dir.join("../../registry/features.toml");

    // Only re-run when the TOML changes — touching any other file must not re-run this script.
    println!("cargo:rerun-if-changed={}", toml_path.display());

    let src = std::fs::read_to_string(&toml_path)
        .unwrap_or_else(|e| panic!("registry/features.toml: cannot read: {e}"));

    // Strip UTF-8 BOM if present — relevant for Windows contributors.
    let src = src.strip_prefix('\u{FEFF}').unwrap_or(&src);

    let doc: toml::Value = toml::from_str(src)
        .unwrap_or_else(|e| panic!("registry/features.toml: TOML parse error: {e}"));

    let table = doc
        .as_table()
        .expect("registry/features.toml: top level must be a TOML table");

    let mut out = String::new();
    writeln!(
        out,
        "// Generated by crates/ynz-registry/build.rs — do not edit."
    )
    .unwrap();
    writeln!(out, "// Source: registry/features.toml").unwrap();
    writeln!(out).unwrap();

    emit_keywords(table, &mut out);
    emit_banned_declaration_keywords(table, &mut out);
    emit_banned_jargon(table, &mut out);
    emit_primitive_intrinsics(table, &mut out);
    emit_type_attached_constants(table, &mut out);
    emit_deferred_language_features(table, &mut out);
    emit_deferred_tooling_features(table, &mut out);
    emit_diagnostic_templates(table, &mut out);
    emit_muted_hint_domains(table, &mut out);
    emit_lint_rules(table, &mut out);

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    std::fs::write(out_dir.join("registry.rs"), &out)
        .unwrap_or_else(|e| panic!("failed to write OUT_DIR/registry.rs: {e}"));
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

type TomlTable = toml::map::Map<String, toml::Value>;

fn get_str<'a>(entry: &'a TomlTable, key: &str, kind: &str, entry_name: &str) -> &'a str {
    entry
        .get(key)
        .unwrap_or_else(|| {
            panic!("registry/features.toml: [[{kind}]] entry '{entry_name}': missing required field '{key}'")
        })
        .as_str()
        .unwrap_or_else(|| {
            panic!("registry/features.toml: [[{kind}]] entry '{entry_name}': field '{key}' must be a string")
        })
}

fn get_bool(entry: &TomlTable, key: &str, kind: &str, entry_name: &str, default: bool) -> bool {
    match entry.get(key) {
        None => default,
        Some(v) => v.as_bool().unwrap_or_else(|| {
            panic!("registry/features.toml: [[{kind}]] entry '{entry_name}': field '{key}' must be a boolean")
        }),
    }
}

fn get_str_array<'a>(
    entry: &'a TomlTable,
    key: &str,
    kind: &str,
    entry_name: &str,
) -> Vec<&'a str> {
    match entry.get(key) {
        None => vec![],
        Some(v) => {
            let arr = v.as_array().unwrap_or_else(|| {
                panic!("registry/features.toml: [[{kind}]] entry '{entry_name}': field '{key}' must be an array")
            });
            arr.iter()
                .map(|item| {
                    item.as_str().unwrap_or_else(|| {
                        panic!("registry/features.toml: [[{kind}]] entry '{entry_name}': field '{key}' must be an array of strings")
                    })
                })
                .collect()
        }
    }
}

fn get_entries<'a>(table: &'a TomlTable, kind: &str) -> Vec<&'a TomlTable> {
    match table.get(kind) {
        None => vec![],
        Some(v) => {
            let arr = v.as_array().unwrap_or_else(|| {
                panic!("registry/features.toml: '{kind}' must be an array of tables")
            });
            arr.iter()
                .map(|item| {
                    item.as_table().unwrap_or_else(|| {
                        panic!("registry/features.toml: each [[{kind}]] entry must be a table")
                    })
                })
                .collect()
        }
    }
}

fn check_no_duplicates(names: &[&str], kind: &str) {
    let mut seen = HashSet::new();
    for name in names {
        if !seen.insert(*name) {
            panic!(
                "registry/features.toml: [[{kind}]] has duplicate entry name '{name}' — \
                 each name must be unique within its kind"
            );
        }
    }
}

fn escape_str_array(items: &[&str]) -> String {
    let mut s = String::from("&[");
    for (i, item) in items.iter().enumerate() {
        if i > 0 {
            s.push_str(", ");
        }
        s.push_str(&format!("{item:?}"));
    }
    s.push(']');
    s
}

// ---------------------------------------------------------------------------
// Per-kind emitters
// ---------------------------------------------------------------------------

fn emit_keywords(table: &TomlTable, out: &mut String) {
    let entries = get_entries(table, "keyword");
    let names: Vec<&str> = entries
        .iter()
        .map(|e| get_str(e, "name", "keyword", "<unknown>"))
        .collect();
    check_no_duplicates(&names, "keyword");

    writeln!(out, "pub static KEYWORDS: &[crate::KeywordEntry] = &[").unwrap();
    for entry in &entries {
        let name = get_str(entry, "name", "keyword", "<unknown>");
        let token = get_str(entry, "token", "keyword", name);
        let since = get_str(entry, "since", "keyword", name);
        let hover_what = entry.get("hover_what").and_then(|v| v.as_str());
        let hover_what_instead = entry.get("hover_what_instead").and_then(|v| v.as_str());
        let hover_why = entry.get("hover_why").and_then(|v| v.as_str());
        let hw = match hover_what {
            Some(s) => format!("Some({s:?})"),
            None => "None".to_string(),
        };
        let hwi = match hover_what_instead {
            Some(s) => format!("Some({s:?})"),
            None => "None".to_string(),
        };
        let hwy = match hover_why {
            Some(s) => format!("Some({s:?})"),
            None => "None".to_string(),
        };
        writeln!(
            out,
            "    crate::KeywordEntry {{ name: {name:?}, token: {token:?}, since: {since:?}, hover_what: {hw}, hover_what_instead: {hwi}, hover_why: {hwy} }},",
        )
        .unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();
}

fn emit_banned_declaration_keywords(table: &TomlTable, out: &mut String) {
    let kind = "banned_declaration_keyword";
    let entries = get_entries(table, kind);
    let names: Vec<&str> = entries
        .iter()
        .map(|e| get_str(e, "name", kind, "<unknown>"))
        .collect();
    check_no_duplicates(&names, kind);

    writeln!(
        out,
        "pub static BANNED_DECLARATION_KEYWORDS: &[crate::BannedDeclarationKeywordEntry] = &["
    )
    .unwrap();
    for entry in &entries {
        let name = get_str(entry, "name", kind, "<unknown>");
        let what_instead = get_str(entry, "what_instead", kind, name);
        let why = get_str(entry, "why", kind, name);
        let since = get_str(entry, "since", kind, name);
        writeln!(
            out,
            "    crate::BannedDeclarationKeywordEntry {{ name: {name:?}, what_instead: {what_instead:?}, why: {why:?}, since: {since:?} }},",
        )
        .unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();
}

fn emit_banned_jargon(table: &TomlTable, out: &mut String) {
    let kind = "banned_jargon";
    let entries = get_entries(table, kind);
    let names: Vec<&str> = entries
        .iter()
        .map(|e| get_str(e, "name", kind, "<unknown>"))
        .collect();
    check_no_duplicates(&names, kind);

    writeln!(
        out,
        "pub static BANNED_JARGON: &[crate::BannedJargonEntry] = &["
    )
    .unwrap();
    for entry in &entries {
        let name = get_str(entry, "name", kind, "<unknown>");
        let replacement = get_str(entry, "replacement", kind, name);
        let reason = get_str(entry, "reason", kind, name);
        let is_acronym = get_bool(entry, "is_acronym", kind, name, false);
        writeln!(
            out,
            "    crate::BannedJargonEntry {{ name: {name:?}, replacement: {replacement:?}, reason: {reason:?}, is_acronym: {is_acronym} }},",
        )
        .unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();
}

fn emit_primitive_intrinsics(table: &TomlTable, out: &mut String) {
    let kind = "primitive_intrinsic";
    let entries = get_entries(table, kind);
    // Overloads with the same name are intentional (e.g. range/1 and range/2) — skip duplicate check.

    writeln!(
        out,
        "pub static PRIMITIVE_INTRINSICS: &[crate::PrimitiveIntrinsicEntry] = &["
    )
    .unwrap();
    for entry in &entries {
        let name = get_str(entry, "name", kind, "<unknown>");
        let intr_kind = get_str(entry, "kind", kind, name);
        let receiver_type = entry.get("receiver_type").and_then(|v| v.as_str());
        let param_types = get_str_array(entry, "param_types", kind, name);
        // return_type is optional for print_type entries (they have no return value).
        let return_type = entry
            .get("return_type")
            .and_then(|v| v.as_str())
            .unwrap_or("");
        let since = get_str(entry, "since", kind, name);
        let doc = entry.get("doc").and_then(|v| v.as_str());

        let receiver_expr = match receiver_type {
            Some(rt) => format!("Some({rt:?})"),
            None => "None".to_string(),
        };
        let params_expr = escape_str_array(&param_types);
        let doc_expr = match doc {
            Some(d) => format!("Some({d:?})"),
            None => "None".to_string(),
        };

        writeln!(
            out,
            "    crate::PrimitiveIntrinsicEntry {{ name: {name:?}, kind: {intr_kind:?}, receiver_type: {receiver_expr}, param_types: {params_expr}, return_type: {return_type:?}, since: {since:?}, doc: {doc_expr} }},",
        )
        .unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();
}

fn emit_type_attached_constants(table: &TomlTable, out: &mut String) {
    let kind = "type_attached_constant";
    let entries = get_entries(table, kind);
    // Uniqueness is (type_name, const_name) composite — same const_name on different types is valid.
    let mut seen = std::collections::HashSet::new();
    for e in &entries {
        let tn = get_str(e, "type_name", kind, "<unknown>");
        let cn = get_str(e, "const_name", kind, tn);
        let key = format!("{tn}.{cn}");
        if !seen.insert(key.clone()) {
            panic!("registry/features.toml: [[{kind}]] has duplicate entry '{key}' — (type_name, const_name) must be unique");
        }
    }

    writeln!(
        out,
        "pub static TYPE_ATTACHED_CONSTANTS: &[crate::TypeAttachedConstantEntry] = &["
    )
    .unwrap();
    for entry in &entries {
        let type_name = get_str(entry, "type_name", kind, "<unknown>");
        let const_name = get_str(entry, "const_name", kind, type_name);
        let value_type = get_str(entry, "value_type", kind, type_name);
        let value_literal = get_str(entry, "value_literal", kind, type_name);
        let since = get_str(entry, "since", kind, type_name);
        writeln!(
            out,
            "    crate::TypeAttachedConstantEntry {{ type_name: {type_name:?}, const_name: {const_name:?}, value_type: {value_type:?}, value_literal: {value_literal:?}, since: {since:?} }},",
        )
        .unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();
}

fn emit_deferred_language_features(table: &TomlTable, out: &mut String) {
    let kind = "deferred_language_feature";
    let entries = get_entries(table, kind);
    let names: Vec<&str> = entries
        .iter()
        .map(|e| get_str(e, "name", kind, "<unknown>"))
        .collect();
    check_no_duplicates(&names, kind);

    writeln!(
        out,
        "pub static DEFERRED_LANGUAGE_FEATURES: &[crate::DeferredLanguageFeatureEntry] = &["
    )
    .unwrap();
    for entry in &entries {
        let name = get_str(entry, "name", kind, "<unknown>");
        let substitute = get_str(entry, "substitute", kind, name);
        let why = get_str(entry, "why", kind, name);
        let ships_in = get_str(entry, "ships_in", kind, name);
        let design_doc = get_str(entry, "design_doc", kind, name);
        let triggers = get_str(entry, "triggers", kind, name);
        writeln!(
            out,
            "    crate::DeferredLanguageFeatureEntry {{ name: {name:?}, substitute: {substitute:?}, why: {why:?}, ships_in: {ships_in:?}, design_doc: {design_doc:?}, triggers: {triggers:?} }},",
        )
        .unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();
}

fn emit_deferred_tooling_features(table: &TomlTable, out: &mut String) {
    let kind = "deferred_tooling_feature";
    let entries = get_entries(table, kind);
    let names: Vec<&str> = entries
        .iter()
        .map(|e| get_str(e, "name", kind, "<unknown>"))
        .collect();
    check_no_duplicates(&names, kind);

    writeln!(
        out,
        "pub static DEFERRED_TOOLING_FEATURES: &[crate::DeferredToolingFeatureEntry] = &["
    )
    .unwrap();
    for entry in &entries {
        let name = get_str(entry, "name", kind, "<unknown>");
        let substitute = get_str(entry, "substitute", kind, name);
        let why = get_str(entry, "why", kind, name);
        let ships_in = get_str(entry, "ships_in", kind, name);
        let design_doc = get_str(entry, "design_doc", kind, name);
        let triggers = get_str(entry, "triggers", kind, name);
        writeln!(
            out,
            "    crate::DeferredToolingFeatureEntry {{ name: {name:?}, substitute: {substitute:?}, why: {why:?}, ships_in: {ships_in:?}, design_doc: {design_doc:?}, triggers: {triggers:?} }},",
        )
        .unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();
}

fn emit_diagnostic_templates(table: &TomlTable, out: &mut String) {
    let kind = "diagnostic_template";
    let entries = get_entries(table, kind);
    let names: Vec<&str> = entries
        .iter()
        .map(|e| get_str(e, "kind_name", kind, "<unknown>"))
        .collect();
    check_no_duplicates(&names, kind);

    writeln!(
        out,
        "pub static DIAGNOSTIC_TEMPLATES: &[crate::DiagnosticTemplateEntry] = &["
    )
    .unwrap();
    for entry in &entries {
        let kind_name = get_str(entry, "kind_name", kind, "<unknown>");
        let what = get_str(entry, "what_template", kind, kind_name);
        let what_instead = get_str(entry, "what_instead_template", kind, kind_name);
        let why = get_str(entry, "why_template", kind, kind_name);
        writeln!(
            out,
            "    crate::DiagnosticTemplateEntry {{ kind_name: {kind_name:?}, what_template: {what:?}, what_instead_template: {what_instead:?}, why_template: {why:?} }},",
        )
        .unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();
}

fn emit_lint_rules(table: &TomlTable, out: &mut String) {
    let kind = "lint_rule";
    let entries = get_entries(table, kind);
    let names: Vec<&str> = entries
        .iter()
        .map(|e| get_str(e, "name", kind, "<unknown>"))
        .collect();
    check_no_duplicates(&names, kind);

    writeln!(out, "pub static LINT_RULES: &[crate::LintRuleEntry] = &[").unwrap();
    for entry in &entries {
        let name = get_str(entry, "name", kind, "<unknown>");
        let severity = get_str(entry, "severity", kind, name);
        // A lint rule is a teaching surface, never a gate: Tier 3 lints are dismissable
        // suggestions (IMP-linting.md); "error" would let a lint block a compile.
        if !matches!(severity, "suggestion" | "warning") {
            panic!(
                "registry/features.toml: [[{kind}]] entry '{name}': \
                 severity must be 'suggestion' or 'warning' (a lint is never an error — \
                 Tier 3 lints are teaching surfaces per IMP-linting.md) — got '{severity}'"
            );
        }
        let description = get_str(entry, "description", kind, name);
        let what = get_str(entry, "what_template", kind, name);
        let what_instead = get_str(entry, "what_instead_template", kind, name);
        let why = get_str(entry, "why_template", kind, name);
        let since = get_str(entry, "since", kind, name);
        let design_doc = get_str(entry, "design_doc", kind, name);
        writeln!(
            out,
            "    crate::LintRuleEntry {{ name: {name:?}, severity: {severity:?}, description: {description:?}, what_template: {what:?}, what_instead_template: {what_instead:?}, why_template: {why:?}, since: {since:?}, design_doc: {design_doc:?} }},",
        )
        .unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();
}

fn emit_muted_hint_domains(table: &TomlTable, out: &mut String) {
    let kind = "muted_hint_domain";
    let entries = get_entries(table, kind);
    let names: Vec<&str> = entries
        .iter()
        .map(|e| get_str(e, "domain", kind, "<unknown>"))
        .collect();
    check_no_duplicates(&names, kind);

    writeln!(
        out,
        "pub static MUTED_HINT_DOMAINS: &[crate::MutedHintDomainEntry] = &["
    )
    .unwrap();
    for entry in &entries {
        let domain = get_str(entry, "domain", kind, "<unknown>");
        let placement = get_str(entry, "placement_category", kind, domain);
        // Validate placement_category is one of the three legal values.
        if !matches!(placement, "Addition" | "Replacement" | "Informational") {
            panic!(
                "registry/features.toml: [[{kind}]] entry '{domain}': \
                 placement_category must be 'Addition', 'Replacement', or 'Informational' — got '{placement}'"
            );
        }
        let description = get_str(entry, "description", kind, domain);
        let example_source = get_str(entry, "example_source", kind, domain);
        let example_hint = get_str(entry, "example_hint_rendered", kind, domain);
        let hover_what = entry.get("hover_what").and_then(|v| v.as_str());
        let hover_what_instead = entry.get("hover_what_instead").and_then(|v| v.as_str());
        let hover_why = entry.get("hover_why").and_then(|v| v.as_str());
        let hw = match hover_what {
            Some(s) => format!("Some({s:?})"),
            None => "None".to_string(),
        };
        let hwi = match hover_what_instead {
            Some(s) => format!("Some({s:?})"),
            None => "None".to_string(),
        };
        let hwy = match hover_why {
            Some(s) => format!("Some({s:?})"),
            None => "None".to_string(),
        };
        writeln!(
            out,
            "    crate::MutedHintDomainEntry {{ domain: {domain:?}, placement_category: {placement:?}, description: {description:?}, example_source: {example_source:?}, example_hint_rendered: {example_hint:?}, hover_what: {hw}, hover_what_instead: {hwi}, hover_why: {hwy} }},",
        )
        .unwrap();
    }
    writeln!(out, "];").unwrap();
}
